### ISSUE TITLE
Check Sumw2 handling in histograms

### ISSUE THREAD

**Issue by ferencek** [CMS-H3PO/H3PO#10]
Initial histograms used in the analysis are from the Python Hist package which are later stored as ROOT histograms. Handling of event weights needs to be checked since they are relevant for MC statistical uncertainties.

**Comment by mroguljic** [comment]
The second part of this notebook shows how to initialize a `Hist` that stores weights and checks that it correctly saves it in ROOT histograms.

https://github.com/CMS-H3PO/H3PO/blob/main/notebooks/Playground-Matej.ipynb

**Comment by mroguljic** [comment]
I also added a check to test if the error is properly calculated with `hist *= scale` to the notebook. As expected, everything works correctly. Closing this issue.
